var languages = {
  af: "Afrikaans",
  Arabic: "ar",
  "Bosnian (latin)": "bs-Latn",
  Bulgarian: "bg",
  Catalan: "ca",
  "Chinese simplified": "zh-CHS",
  "Chinese traditional": "zh-CHT",
  Croatian: "hr",
  Czech: "cs",
  Danish: "da",
  Dutch: "nl",
  English: "en",
  Estonian: "et",
  Finnish: "fi",
  French: "fr",
  German: "de",
  Greek: "el",
  "Haitian creole": "ht",
  Hebrew: "he",
  Hindi: "hi",
  "Hmong daw": "mww",
  Hungarian: "hu",
  Indonesian: "id",
  Italian: "it",
  Japanese: "ja",
  Kiswahili: "sw",
  Klingon: "tlh",
  "Klingon (piqad)": "tlh-Qaak",
  Korean: "ko",
  Latvian: "lv",
  Lithuanian: "lt",
  Malay: "ms",
  Maltese: "mt",
  Norwegian: "no",
  Persian: "fa",
  Polish: "pl",
  Portuguese: "pt",
  "Querétaro otomi": "otq",
  Romanian: "ro",
  Russian: "ru",
  "Serbian (cyrillic)": "sr-Cyrl",
  "Serbian (latin)": "sr-Latn",
  Slovak: "sk",
  Slovenian: "sl",
  Spanish: "es",
  Swedish: "sv",
  Thai: "th",
  Turkish: "tr",
  Ukrainian: "uk",
  Urdu: "ur",
  Vietnamese: "vi",
  Welsh: "cy",
  "Yucatec maya": "yua"
}

module.exports = languages;
